name = "irwin-studio-backend"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = ""
entry-point = "./src/index.ts"
workers_dev = true
route = ""
zone_id = ""

[env.staging]
name = "is-be-staging"
